Update for test
jacob-armiger/arduino-motor-control pull request #1
Opened 2021-06-15 12:19 UTC by mbranuncc

Removed blocking on SD card fail and added battery monitoring

2021-06-15 12:47 UTC, jacob-armiger requested changes

2021-06-15 12:47 UTC, jacob-armiger commented on freq_read/freq_read.ino
> +  Serial.println("SD Card initialization done.");
SD card error checking needs fix

2021-06-15 12:47 UTC, jacob-armiger commented on freq_read/freq_read.ino
> +  double dv = ( 5.0 * analogRead( A0 ) ) / 1024.0;
A comment on what these variables are, or more descriptive variable names would be helpful👍🏻

2021-07-08 03:04 UTC, closed without merging

2021-07-08 03:04 UTC, mbranuncc commented
This isn't relevant any more.